const products = [
  {
    id: 1,
    user: "admin",
    name: "Dodge SRT",
    description: "Пробег: 1500км, Один хозяин.",
    price: 38743.39,
    type: "auto",
    unique: 5,
  },
  {
    id: 2,
    user: "admin",
    name: "Ford Mustang",
    description: "Пробег 3000км. не битая, косяков нет.",
    price: 78922.26,
    type: "auto",
    unique: 7,
  },
  {
    id: 3,
    user: "admin",
    name: "Ford mustang",
    description: "Пробег 50000км. 35 хозяев, битая!!!",
    price: 99987.73,
    type: "auto",
    unique: 9,
  },
  {
    id: 4,
    user: "admin",
    name: "Maserati",
    description:
      " Пробег 0км. ездить боялись так как ремонт дорогой, 1 хозяин.",
    price: 43383.23,
    type: "auto",
    unique: 1,
  },
  {
    id: 5,
    user: "admin",
    name: "Porsche 911",
    description: "Пробег 30000км. едет бодро, коптит жрет масло бочками.",
    price: 87433.23,
    type: "auto",
    unique: 14,
  },
  {
    id: 6,
    user: "admin",
    name: "Dodge challenger",
    description: "Пробег 100000км. Машина  хочет едет, хочет не едет!!!",
    price: 48674.09,
    type: "auto",
    unique: 15,
  },
  {
    id: 7,
    user: "admin",
    name: "Peugeot",
    description: "Пробег 129км. 1 хозяин. в основном только ломается.",
    price: 70993.86,
    type: "auto",
    unique: 3,
  },
  {
    id: 8,
    user: "admin",
    name: "BMW",
    description: "Пробег 0км. Новая машина, масло жрет тоннами",
    price: 74634.13,
    type: "auto",
    unique: 8,
  },
  {
    id: 9,
    user: "admin",
    name: "Audi",
    description: "Пробег 0км. Красный цвет, обещают внимание на дороге!",
    price: 12344.46,
    type: "auto",
    unique: 10,
  },
  {
    id: 10,
    user: "admin",
    name: "yamaha fz",
    description: "Пробег 0км.черный цвет, пуля!",
    price: 35812.36,
    type: "moto",
    unique: 2,
  },
  {
    id: 11,
    user: "admin",
    name: "finval",
    description: "Пробег 50часов. Красный цвет, ловила топляки!",
    price: 95614.16,
    type: "boat",
    unique: 18,
  },
  {
    id: 12,
    user: "admin",
    name: "yamaha r6",
    description: "Пробег 0км. Синий цвет, обещают внимание на дороге!",
    price: 73251.36,
    type: "moto",
    unique: 11,
  },
  {
    id: 13,
    user: "admin",
    name: "crownline",
    description: "Пробег 50часов. белый цвет, вместительный!",
    price: 41334.56,
    type: "boat",
    unique: 17,
  },
  {
    id: 14,
    user: "admin",
    name: "realcraft",
    description: "Пробег 30часов Черный цвет, обещают много рыбы!",
    price: 14242.36,
    type: "boat",
    unique: 12,
  },
  {
    id: 15,
    user: "admin",
    name: "ducati",
    description: "Пробег 0км. черный цвет, пуля, без проблем!",
    price: 12223.46,
    type: "moto",
    unique: 6,
  },
  {
    id: 16,
    user: "admin",
    name: "honda",
    description: "Пробег 0км. Красный цвет, обещают много адреналина!",
    price: 42343.46,
    type: "moto",
    unique: 4,
  },
  {
    id: 17,
    user: "admin",
    name: "silver",
    description:
      "Пробег 59часов. лучшее предложение по соотношению цены и качества!",
    price: 46223.46,
    type: "boat",
    unique: 13,
  },
];

module.exports = products;
